trigger:
  branches:
    include:
      - main  # Replace with your branch name if different

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.x'  # Replace with the appropriate .NET SDK version

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: dotnet build --configuration Release --output ./build
  displayName: 'Build the project'

- script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish the project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'