trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '5.x'  # Replace with the appropriate .NET SDK version

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'  # Adjust the pattern to match your project structure

- task: DotNetCoreCLI@2
  displayName: 'Run application'
  inputs:
    command: 'run'
    projects: '**/*.csproj'  # Adjust the pattern to match your main application project
    arguments: '--configuration Release'

- task: PublishPipelineArtifact@1
  displayName: 'Publish artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
